[package]
name = "lme2-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-to-many = { version = "^0.1.7", features = ["serde"] }
nalgebra = "0.32.3"
rayon = "1.8.0"
